### PR TITLE
SysV shared memory APIs

### PR DESCRIPTION
**Pull request by polachok**
Let's start small and see what CI says

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! I just merged another PR and it looks like this has some intermittent errors (don't worry about the Windows errors for now), so could you rebase/push to trigger again?

**Comment by alexcrichton** [comment]
Looks like some more legit travis failures

**Comment by alexcrichton** [comment]
MUSL + MIPS weirdness?

**Comment by polachok** [comment]
business as usual

**Comment by alexcrichton** [comment]
Thanks!

**Pull request merged**
