### PR TITLE
Add ioctl constants

### PR DESCRIPTION
**Pull request by derekdreery**
Add some constants for ioctl calls.

### CODE REVIEW

**Comment by semarie** [comment]
I don't think the constants are the same for all unix.
For example, under OpenBSD, these constants have differents values.

**Comment by derekdreery** [comment]
Will the ci pick that up?

**Comment by derekdreery** [comment]
The CI has picked it up :)

**Comment by derekdreery** [comment]
It seems that android uses int, whereas linux uses unsigned long for the __request in ioctl - so constants need to be different types for android and not android.

**Comment by derekdreery** [comment]
I don't understand the mips error

**Comment by alexcrichton** [comment]
Yeah the build failures are unrelated, and the constants for other platforms can be added in time (hard to do so without CI), thanks @derekdreery!

I'll work on merging this with a few others all at once

**Comment by derekdreery** [comment]
:D

**Comment by alexcrichton** [comment]
To link things up, landed in https://github.com/rust-lang-nursery/libc/pull/134

**Pull request merged**
