### PR TITLE
Fixes #144 by defining O_ACCMODE for BSD's

### LINKED ISSUE #144: O_ACCMODE node defined for BSD's
Breaking the build for FreeBSD, Bitrig, OpenBSD, DragonflyBSD, NetBSD.

### PR DESCRIPTION
**Pull request by dhuseby**
fixes the current build breaker.

### CODE REVIEW

**Comment by dhuseby** [comment]
I'm not sure why the openbsd build failed.  @alexcrichton is the openbsd CI working?  I'll do a local build with my patch to see if it works.

**Comment by semarie** [comment]
the openbsd failure is due to unresponsiveness of mirror used by buildbot for download openbsd packages.

**Comment by alexcrichton** [comment]
@semarie do you know if that's a common occurrence? I can try to bundle everything on the disk image or download from a different location if it happens frequently.

**Comment by semarie** [comment]
@alexcrichton it shouldn't be common. But you should be able to failover over multiples mirrors with:

```
installpath = http://somesite/pub/OpenBSD/%c/packages/%a/
installpath += http://othersite/pub/OpenBSD/%c/packages/%a/
```

inside `/etc/pkg.conf`. The mirror list is at http://www.openbsd.org/ftp.html

**Comment by alexcrichton** [comment]
Thanks for the tip! If this happens frequently I'll look into an image doing that.

**Comment by dhuseby** [comment]
@alexcrichton alright, we're all green.  can you merge this please?

**Comment by dhuseby** [comment]
@alexcrichton once this lands, what is the procedure for updating the submodule dependency in the main rust repo?  is there a formal process or should i just update it in my branch and do a PR?

**Comment by alexcrichton** [comment]
Indeed I can merge!

Yeah feel free to just send a PR to the rust-lang/rust repo with this update, it should be pretty easy to sail through

**Pull request merged**
