### PR TITLE
POSIX sched_* APIs

### PR DESCRIPTION
**Pull request by polachok**
Let's see what CI says. Will add constants later.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Looks like the definition of `sched_param` may be tweaked among various platforms, and perhaps the functions could be moved to `src/unix/notbsd/mod.rs` to auto-exclude OSX? I'm also not sure if these exist in the FreeBSD/OpenBSD-like systems.

**Comment by polachok** [comment]
It [exists](https://www.freebsd.org/cgi/man.cgi?query=sched_getscheduler&sektion=2) in freebsd and dragonfly. Not OpenBSD, though.

**Comment by alexcrichton** [comment]
Ah ok, perhaps the definitions could be copied between `src/unix/notbsd/mod.rs` and `src/unix/bsd/freebsdlike/mod.rs`?

**Comment by polachok** [comment]
Damn it, musl, [what's wrong with you](https://fossies.org/dox/musl-1.0.5/structsched__param.html)?

**Comment by alexcrichton** [comment]
Looks like MIPS is a bit funny for Linux?

**Comment by polachok** [comment]
I think it's just super old glibc in CI. 2.11? I have 2.15 on my ubuntu 12.04.

**Comment by alexcrichton** [comment]
Ah yeah that may be the case, unfortunately the mips compiler is super old I think.

You can add exceptions to build.rs for now to get this through if you want saying "if we're mips linux don't check this value"

**Comment by polachok** [comment]
Ok, I did that. Also added sched_get_priority_*

**Comment by alexcrichton** [comment]
Thanks!

**Pull request merged**
