### PR TITLE
Offer a c_bool

### PR DESCRIPTION
**Pull request by solidsnack**

### CODE REVIEW

**Comment by jimblandy** [comment]
Pull request #128 is similar to this.

**Comment by brson** [comment]
Thanks! Since #128 comes with tests, and the typedef definition that I think we'll prefer, I'm going to close this in favor of that.

**Comment by solidsnack** [comment]
It seems like #128 is a way's away from doing the right thing semantically, with respect to allowed values of bool.

**Comment by jimblandy** [comment]
> It seems like #128 is a way's away from doing the right thing semantically, with respect to allowed values of bool.

How so? Both C and Rust constrain `bool` values to be either zero or one.

**Comment by solidsnack** [comment]
@jimblandy Maybe I'm missing something but the definition of `c_bool` in #128 is `pub type c_bool = u8;`. Is there supposed to be a conversion somewhere?

**Comment by jimblandy** [comment]
@solidsnack You are not missing something, I screwed up! Man... [re-pushes]

**Pull request closed without merging**
