### PR TITLE
Add IP v6 group membership options to OpenBSD build

### PR DESCRIPTION
**Pull request by polezaivsani**
Add IPV6_JOIN_GROUP and IPV6_LEAVE_GROUP sockopt constants.

### CODE REVIEW

**Comment by polezaivsani** [comment]
Excuse me being a tad impatient, but should you merge this in, can we get a version bump as i'd like to update another library (net2-rs) with related changes and going with the same version migh cause minor annoyance.

**Comment by alexcrichton** [comment]
Ah looks like the tests were run against an older version of master, could you rebase and re-push?

And yeah I can make a release after this is merged.

**Comment by polezaivsani** [comment]
Here's a fresh one!

**Comment by alexcrichton** [comment]
Thanks!

**Pull request merged**
