### PR TITLE
Add a pinch of KERN_PROC_* consts to OpenBSD family

### PR DESCRIPTION
**Pull request by polezaivsani**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Unfortunately github won't allow a merge of a branch which isn't up-to-date, could you rebase and force-push? I'll merge once CI is green again

**Comment by alexcrichton** [comment]
Oh actually https://github.com/rust-lang-nursery/libc/pull/171 is also ready to go and needs a rebase so I'll just roll them together

**Comment by alexcrichton** [comment]
(in https://github.com/rust-lang-nursery/libc/pull/175)

**Comment by polezaivsani** [comment]
Thanks, man!

**Pull request closed without merging**
