### PR TITLE
Add poll API

### PR DESCRIPTION
**Pull request by diwic**
You seem to have a very ambitious CI system here, so I'm just going to throw my code at that and see if it builds :-)

### CODE REVIEW

**Comment by steveklabnik** [comment]
This will need a rebase, at least.

**Comment by diwic** [comment]
@steveklabnik, thanks - rebase on top of what? Or do you mean I should squash the "Add Poll API" and "Fix poll API" commits?

**Comment by diwic** [comment]
Ok, I squashed them now. The only failing build is mips (unless I failed to squash them correctly!) and, from what I can understand, it seems unrelated to my poll API addition, so I suppose this can be merged?

**Comment by steveklabnik** [comment]
2015-12-25-194742_140x120_scrot


this icon to me says 'rebase', but github has been messing with their UI lately, so maybe it's because of the failing CI.

**Comment by diwic** [comment]
Mips build fails with the following error:

    error: linking with `mips-linux-gnu-gcc` failed: exit code: 1
    /usr/lib/gcc/mips-linux-gnu/4.4.5/../../../../mips-linux-gnu/bin/ld: Dwarf Error: found dwarf version '4', this reader only handles version 2 and 3 information.
    /usr/lib/gcc/mips-linux-gnu/4.4.5/../../../../mips-linux-gnu/bin/ld: Dwarf Error: found dwarf version '0', this reader only handles version 2 and 3 information.
    /usr/lib/gcc/mips-linux-gnu/4.4.5/../../../../mips-linux-gnu/bin/ld: Dwarf Error: found dwarf version '0', this reader only handles version 2 and 3 information.
    /usr/lib/gcc/mips-linux-gnu/4.4.5/../../../../mips-linux-gnu/bin/ld: Dwarf Error: found dwarf version '3072', this reader only handles version 2 and 3 information.
    error: aborting due to previous error

This is the only failed build and it does not seem related to the addition of the poll API, unless I'm missing something?

**Comment by diwic** [comment]
Should be okay rebase wise - I forked this yesterday, and the last commit is a few days old.

**Comment by alexcrichton** [comment]
Thanks @diwic! The mips failures look unrelated, so I'll work on getting this merged with a few others as well.

**Comment by alexcrichton** [comment]
To link things up, landed in https://github.com/rust-lang-nursery/libc/pull/134

**Comment by diwic** [comment]
Thanks!

**Pull request merged**
