### PR TITLE
Add getxattr()/setxattr() variations

### PR DESCRIPTION
**Pull request by polachok**

### CODE REVIEW

**Comment by polachok** [comment]
It seems like android has [xattr.h](https://github.com/android/platform_bionic/blob/master/libc/include/sys/xattr.h) since 2012?

**Comment by alexcrichton** [comment]
It could be because we're using an older android toolchain which doesn't have these headers just yet. The CI image we're using is attempting to be upgraded in #70 but Travis apparently doesn't like the new image...

**Comment by alexcrichton** [comment]
Yeah I'm fine moving these to just linux, but looks like the header doesn't exist on android either?

Also could you be sure to format the definitions to 80 characters?

**Comment by polachok** [comment]
Ok, done

**Comment by alexcrichton** [comment]
Thanks!

**Pull request merged**
